# Generated by Django 5.1.3 on 2024-11-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=1)),
                ('photo', models.ImageField(upload_to='photos_clients/')),
            ],
        ),
        migrations.CreateModel(
            name='Code_Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('date_de_point', models.DateTimeField(auto_now_add=True)),
                ('utilise', models.BooleanField()),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Point_Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recette', models.IntegerField()),
                ('date_de_point', models.DateTimeField(auto_now_add=True)),
                ('immatriculation_auto', models.CharField(max_length=14)),
                ('Chauffeur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='chauffeur_detect.chauffeurs')),
            ],
        ),
    ]
