# Generated by Django 5.1.3 on 2024-12-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeur_detect', '0002_chauffeurs_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_verification',
            name='utilise',
            field=models.BooleanField(default=False),
        ),
    ]
