# Generated by Django 5.1.1 on 2025-03-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chauffeur_detect", "0003_alter_code_verification_utilise"),
    ]

    operations = [
        migrations.AddField(
            model_name="chauffeurs",
            name="employeur_precedant",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chauffeurs",
            name="experience_pro",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chauffeurs",
            name="lieu_habitation",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chauffeurs",
            name="lieu_naissance",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chauffeurs",
            name="niveau_etude",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chauffeurs",
            name="num_en_cas_urgence",
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="chauffeurs",
            name="numero_CNI",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="chauffeurs",
            name="numero_tel",
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="chauffeurs",
            name="personne_en_cas_urgence",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chauffeurs",
            name="situation_matrimoniale",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="point_recette",
            name="km",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
