# Generated by Django 5.1.1 on 2025-03-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chauffeur_detect", "0004_chauffeurs_employeur_precedant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chauffeurs",
            name="employeur_precedant",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="chauffeurs",
            name="experience_pro",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="chauffeurs",
            name="niveau_etude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
